services:
    NetBull\SecurityBundle\Fingerprints\Browser:
        arguments: [ '@logger', '@Psr\Cache\CacheItemPoolInterface' ]
        tags: { name: netbull_security.fingerprint }

    NetBull\SecurityBundle\Fingerprints\Ip:
        tags: { name: netbull_security.fingerprint }
