services:
    NetBull\SecurityBundle\Managers\SecurityManager:
        arguments: [ '', '', '', '', '', '', '@doctrine.orm.default_entity_manager', '@logger' ]
        public: true

    netbull_security.security_listener:
        class: NetBull\SecurityBundle\Security\SecurityListener
        arguments: [ '@NetBull\SecurityBundle\Managers\SecurityManager', '@router', '', '' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }
